name: Octo Organization CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Compile
      run: echo Hello, world!
    
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project
        
  DeployTest:
    name: Deploy to Test
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Deploy step 1
        run: echo deploying to test
        
  DeployProd:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy to prod step 1
        run: echo I am deploying to prod
      
